# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CcPreview < Formula
  desc "Browse and preview images pasted into Claude Code sessions"
  homepage "https://github.com/Watari995/cc-preview"
  version "0.1.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/Watari995/cc-preview/releases/download/v0.1.0/cc-preview_darwin_amd64.tar.gz"
    sha256 "1063633b43f0e8a8974e95018932cad0a45c38de4b50df67d2457693f830ea31"

    define_method(:install) do
      bin.install "cc-preview"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/Watari995/cc-preview/releases/download/v0.1.0/cc-preview_darwin_arm64.tar.gz"
    sha256 "ce78bb0f8d74f44365b749fc816b19797f4fb9b59408f5774dfbe8fa41b70085"

    define_method(:install) do
      bin.install "cc-preview"
    end
  end

  test do
    system "#{bin}/cc-preview version"
  end
end
