# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CcPreview < Formula
  desc "Browse and preview images pasted into Claude Code sessions"
  homepage "https://github.com/Watari995/cc-preview"
  version "0.2.1"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/Watari995/cc-preview/releases/download/v0.2.1/cc-preview_darwin_amd64.tar.gz"
    sha256 "97403185c2cdadcc4a8b79ed7ae833c2168272785070e7077a8876b5d867624f"

    define_method(:install) do
      bin.install "cc-preview"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/Watari995/cc-preview/releases/download/v0.2.1/cc-preview_darwin_arm64.tar.gz"
    sha256 "d6d6bafecc7a5410c3e29bcac3e06194dbdcc783b8f05c5749906b6c20ba8e58"

    define_method(:install) do
      bin.install "cc-preview"
    end
  end

  test do
    system "#{bin}/cc-preview version"
  end
end
